# Generated by Django 3.0.3 on 2020-02-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='raw_tweets',
            fields=[
                ('raw_tweet_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=120, null=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('location', models.CharField(blank=True, max_length=120, null=True)),
                ('profile_url', models.CharField(blank=True, max_length=120, null=True)),
                ('protected', models.CharField(blank=True, max_length=120, null=True)),
                ('description', models.CharField(blank=True, max_length=120, null=True)),
                ('is_verified', models.CharField(blank=True, max_length=120, null=True)),
                ('follower_count', models.CharField(blank=True, max_length=120, null=True)),
                ('friends_count', models.CharField(blank=True, max_length=120, null=True)),
                ('listed_count', models.CharField(blank=True, max_length=120, null=True)),
                ('favourites_count', models.CharField(blank=True, max_length=120, null=True)),
                ('statuses_count', models.CharField(blank=True, max_length=120, null=True)),
                ('profile_created_at', models.CharField(blank=True, max_length=120, null=True)),
                ('profile_banner_url', models.CharField(blank=True, max_length=120, null=True)),
                ('profile_image_url_https', models.CharField(blank=True, max_length=120, null=True)),
                ('default_profile', models.CharField(blank=True, max_length=120, null=True)),
                ('default_profile_image', models.CharField(blank=True, max_length=120, null=True)),
                ('tweet_text', models.TextField(blank=True, null=True)),
                ('tweet_posted_date', models.CharField(blank=True, max_length=120, null=True)),
                ('lang_code', models.CharField(blank=True, max_length=120, null=True)),
                ('tweet_source', models.CharField(blank=True, max_length=120, null=True)),
                ('search_type', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_raw_tweets',
            },
        ),
        migrations.CreateModel(
            name='tbl_analysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('tweets_id', models.IntegerField()),
                ('pos_sum', models.IntegerField()),
                ('pos_neg', models.IntegerField()),
                ('posCount', models.IntegerField()),
                ('negCount', models.IntegerField()),
                ('nullCount', models.IntegerField()),
                ('uid', models.IntegerField()),
                ('analysis_status', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_analysis',
            },
        ),
        migrations.CreateModel(
            name='tbl_api_setting',
            fields=[
                ('api_id', models.AutoField(primary_key=True, serialize=False)),
                ('api_key', models.CharField(blank=True, max_length=120, null=True)),
                ('api_key_secret', models.CharField(blank=True, max_length=120, null=True)),
                ('access_token', models.CharField(blank=True, max_length=120, null=True)),
                ('access_token_secret', models.CharField(blank=True, max_length=120, null=True)),
                ('setting_status', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_api_setting',
            },
        ),
        migrations.CreateModel(
            name='tbl_category_analysis',
            fields=[
                ('cat_analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('tweet_id', models.IntegerField()),
                ('cat_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_category_analysis',
            },
        ),
        migrations.CreateModel(
            name='tbl_crime_categories',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_crime_categories',
            },
        ),
        migrations.CreateModel(
            name='tbl_designation',
            fields=[
                ('designation_id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_designation',
            },
        ),
        migrations.CreateModel(
            name='tbl_faked_account',
            fields=[
                ('fake_account_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('suspicious_level', models.CharField(blank=True, max_length=255, null=True)),
                ('tag_code', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_faked_account',
            },
        ),
        migrations.CreateModel(
            name='tbl_hacked_account',
            fields=[
                ('hacked_account_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('change_start_from', models.DateField()),
                ('change_end_at', models.DateField()),
                ('tag_code', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_hacked_account',
            },
        ),
        migrations.CreateModel(
            name='tbl_headquarter',
            fields=[
                ('HQ_id', models.AutoField(primary_key=True, serialize=False)),
                ('hq_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('phone_no', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_headquarter',
            },
        ),
        migrations.CreateModel(
            name='tbl_messages',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('msg_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('msg_attachment', models.CharField(blank=True, max_length=120, null=True)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('sender_id', models.IntegerField(blank=True, null=True)),
                ('seen_status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_messages',
            },
        ),
        migrations.CreateModel(
            name='tbl_msg_draft',
            fields=[
                ('draft_id', models.AutoField(primary_key=True, serialize=False)),
                ('msg_subject', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('sender_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_msg_draft',
            },
        ),
        migrations.CreateModel(
            name='tbl_reply_msg',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('msg_id', models.IntegerField(blank=True, null=True)),
                ('reply', models.TextField(blank=True, null=True)),
                ('seen_status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_reply_msg',
            },
        ),
        migrations.CreateModel(
            name='tbl_system_setting',
            fields=[
                ('system_setting_id', models.AutoField(primary_key=True, serialize=False)),
                ('system_name', models.CharField(blank=True, max_length=120, null=True)),
                ('system_logo', models.ImageField(blank=True, default='profile_image/twitter_logo.png', null=True, upload_to='profile_image')),
                ('system_lang', models.CharField(blank=True, max_length=120, null=True)),
                ('modified_by', models.IntegerField()),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_system_setting',
            },
        ),
        migrations.CreateModel(
            name='tbl_tweeter_users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=60, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('profile_url', models.CharField(blank=True, max_length=255, null=True)),
                ('protection_status', models.BooleanField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('verification', models.BooleanField(blank=True, null=True)),
                ('followers_count', models.IntegerField()),
                ('friends_count', models.IntegerField()),
                ('listed_count', models.IntegerField()),
                ('favourites_count', models.IntegerField()),
                ('statuses_count', models.IntegerField()),
                ('profile_created_on', models.DateTimeField()),
                ('profile_banner_url', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_image_url_https', models.CharField(blank=True, max_length=255, null=True)),
                ('default_profile', models.BooleanField()),
                ('default_profile_image', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_tweeter_users',
            },
        ),
        migrations.CreateModel(
            name='tbl_tweets',
            fields=[
                ('tweets_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('tweets', models.TextField()),
                ('tweet_posted_date', models.DateTimeField()),
                ('lang_code', models.CharField(blank=True, max_length=10, null=True)),
                ('search_type', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_tweets',
            },
        ),
        migrations.CreateModel(
            name='tbl_user_role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_user_role',
            },
        ),
        migrations.CreateModel(
            name='tbl_users',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=60, null=True)),
                ('last_name', models.CharField(blank=True, max_length=60, null=True)),
                ('email', models.EmailField(blank=True, max_length=80, null=True)),
                ('password', models.CharField(blank=True, max_length=60, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=60, null=True)),
                ('designation_id', models.IntegerField()),
                ('HQ_id', models.IntegerField()),
                ('role_id', models.IntegerField()),
                ('photo', models.ImageField(blank=True, default='profile_image/default_photo.png', null=True, upload_to='profile_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('modified_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_users',
            },
        ),
    ]
