# Generated by Django 3.0.3 on 2020-02-19 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raw_tweets',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='raw_tweets',
            name='created_by',
        ),
    ]
