# Generated by Django 3.0.3 on 2020-02-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0003_tbl_tweeter_users_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_tweets',
            name='tweet_posted_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
