# Generated by Django 3.0.3 on 2020-03-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0004_auto_20200220_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_train_dataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=120, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tbl_train_dataset',
            },
        ),
        migrations.RemoveField(
            model_name='tbl_analysis',
            name='negCount',
        ),
        migrations.RemoveField(
            model_name='tbl_analysis',
            name='nullCount',
        ),
        migrations.RemoveField(
            model_name='tbl_analysis',
            name='posCount',
        ),
        migrations.RemoveField(
            model_name='tbl_analysis',
            name='pos_neg',
        ),
        migrations.RemoveField(
            model_name='tbl_analysis',
            name='pos_sum',
        ),
        migrations.RemoveField(
            model_name='tbl_analysis',
            name='tweets_id',
        ),
        migrations.RemoveField(
            model_name='tbl_analysis',
            name='uid',
        ),
        migrations.AddField(
            model_name='tbl_analysis',
            name='polarity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_analysis',
            name='subjectivity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_analysis',
            name='tweet_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tbl_analysis',
            name='tweet_text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tbl_analysis',
            name='username',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
