# Generated by Django 3.0.3 on 2020-03-01 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0007_remove_tbl_train_dataset_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_analysis',
            name='created_at',
        ),
    ]
