# Generated by Django 3.0.3 on 2020-03-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0010_auto_20200301_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_analysis',
            name='polarity',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_analysis',
            name='subjectivity',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
