# Generated by Django 3.0.3 on 2020-03-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0012_tbl_analysis_profile_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_raw_analysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('tweet_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('tweet_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('username', models.CharField(blank=True, max_length=1000, null=True)),
                ('polarity', models.CharField(blank=True, max_length=1000, null=True)),
                ('subjectivity', models.CharField(blank=True, max_length=1000, null=True)),
                ('profile_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('analysis_status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_raw_analysis',
            },
        ),
    ]
