# Generated by Django 3.0.3 on 2020-03-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0013_tbl_raw_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_analysis',
            name='tweet_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_raw_analysis',
            name='tweet_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
