# Generated by Django 3.0.3 on 2020-03-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fyp', '0014_auto_20200302_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_analysis',
            name='tweet_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_raw_analysis',
            name='tweet_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
